""" Added users table

Revision ID: 55f9e8082b95
Revises: 
Create Date: 2026-08-04 20:51:12.411087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f9e8082b95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('village', sa.String(length=50), nullable=True),
    sa.Column('farmer_type', sa.String(length=50), nullable=True),
    sa.Column('land_size', sa.Float(), nullable=True),
    sa.Column('preferred_language', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
