"""add_disease_translations

Revision ID: 8149a3f26155
Revises: 2a198be32603
Create Date: 2026-08-18 21:54:39.753710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8149a3f26155'
down_revision = '2a198be32603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_disease_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('treatment_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recovery_fertilizer_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_disease_reports', schema=None) as batch_op:
        batch_op.drop_column('recovery_fertilizer_json')
        batch_op.drop_column('treatment_json')
        batch_op.drop_column('description_json')

    # ### end Alembic commands ###
